version: '3'

services:  
  spring-mysql:    
    container_name: spring-mysql
    image: jaredgary/spring-mysql
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'    
    ports:
      - '9001:9001'
    networks:
      - database_net
      - rabbit_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
        
volumes:
  db-data:
  
networks:
  rabbit_net:
    driver: bridge
  database_net:
    driver: bridge