version: '3'

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - database_net
    deploy:
      replicas: 1
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - database_net
    deploy:
      replicas: 1
    
volumes:
  db-data:
  
networks:
  database_net:
    driver: overlay