version: '3'

services:  
  spring-mysql:
    image: jaredgary/spring-mysql
    ports:
      - '9001:9001'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://172.31.47.219:3306/example?autoReconnect=true&useSSL=false'
      SPRING_PROFILES_ACTIVE: 'prod'
    networks:
      - database_net
    deploy:
      replicas: 3
    
networks:
  database_net:
    driver: overlay