version: '3'

services:
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - database_net
      
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - database_net
        
volumes:
  db-data:
  
networks:
  database_net:
    driver: bridge